// <auto-generated />
using user.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace Api_agencia.Migrations
{
  [DbContext(typeof(ApiDbContext))]
  [Migration("20221105183253_inicio")]
  partial class inicio
  {
    protected override void BuildTargetModel(ModelBuilder modelBuilder)
    {
#pragma warning disable 612, 618
      modelBuilder
          .HasAnnotation("ProductVersion", "6.0.10")
          .HasAnnotation("Relational:MaxIdentifierLength", 64);

      modelBuilder.Entity("Api_agencia.Models.Cliente", b =>
          {
            b.Property<long>("Id")
                      .ValueGeneratedOnAdd()
                      .HasColumnType("bigint");

            b.Property<string>("Cidade")
                      .IsRequired()
                      .HasMaxLength(100)
                      .HasColumnType("varchar(100)");

            b.Property<string>("Cpf")
                      .IsRequired()
                      .HasMaxLength(14)
                      .HasColumnType("varchar(14)");

            b.Property<string>("Email")
                      .IsRequired()
                      .HasMaxLength(100)
                      .HasColumnType("varchar(100)");

            b.Property<string>("Logradouro")
                      .IsRequired()
                      .HasMaxLength(100)
                      .HasColumnType("varchar(100)");

            b.Property<string>("Nome")
                      .IsRequired()
                      .HasMaxLength(100)
                      .HasColumnType("varchar(100)");

            b.Property<string>("Senha")
                      .IsRequired()
                      .HasMaxLength(20)
                      .HasColumnType("varchar(20)");

            b.Property<string>("Tel")
                      .IsRequired()
                      .HasMaxLength(15)
                      .HasColumnType("varchar(15)");

            b.HasKey("Id");

            b.ToTable("cliente");
          });
#pragma warning restore 612, 618
    }
  }
}
