// <auto-generated />
using user.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;

#nullable disable

namespace Api_agencia.Migrations
{
  [DbContext(typeof(ApiDbContext))]
  partial class ApiDbContextModelSnapshot : ModelSnapshot
  {
    protected override void BuildModel(ModelBuilder modelBuilder)
    {
#pragma warning disable 612, 618
      modelBuilder
          .HasAnnotation("ProductVersion", "6.0.10")
          .HasAnnotation("Relational:MaxIdentifierLength", 64);

      modelBuilder.Entity("Api_agencia.Models.Cliente", b =>
          {
            b.Property<long>("Id")
                      .ValueGeneratedOnAdd()
                      .HasColumnType("bigint");

            b.Property<string>("Cpf")
                      .IsRequired()
                      .HasMaxLength(14)
                      .HasColumnType("varchar(14)");

            b.Property<string>("Email")
                      .IsRequired()
                      .HasMaxLength(100)
                      .HasColumnType("varchar(100)");

            b.Property<string>("Nome")
                      .IsRequired()
                      .HasMaxLength(100)
                      .HasColumnType("varchar(100)");

            b.Property<string>("Senha")
                      .IsRequired()
                      .HasMaxLength(20)
                      .HasColumnType("varchar(20)");

            b.HasKey("Id");

            b.ToTable("cliente");
          });
#pragma warning restore 612, 618
    }
  }
}
